# Documentation
# https://nikitabobko.github.io/AeroSpace/guide

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
after-startup-command = ['layout v_accordion', 'mode main']

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# You can set 0 to disable the padding feature
accordion-padding = 20

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'

# Possible values: horizontal|vertical|auto
default-root-container-orientation = 'vertical'

key-mapping.preset = 'qwerty'

# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']


# In this example, 24 is a default value when there is no match.
[gaps]
inner.horizontal = 14
inner.vertical =   14
outer.left =       14
outer.bottom =     15
outer.top =        [{ monitor.main = 14 }, { monitor.secondary = 14 }, { monitor."BenQ GW2765"= 52 }, 24]
outer.right =      15


[mode.main.binding] # 'main' binding mode must be always presented

ctrl-alt-cmd-slash = ['mode service']

ctrl-alt-cmd-i = 'workspace --no-stdin prev'
ctrl-alt-cmd-o = 'workspace --no-stdin next'
ctrl-alt-cmd-minus = ['resize smart -200']
ctrl-alt-cmd-equal = ['resize smart +200']

#ctrl-alt-cmd-h = ['exec-and-forget aerospace focus left --boundaries-action fail || aerospace workspace prev']
ctrl-alt-cmd-h = ['exec-and-forget aerospace focus left --boundaries-action fail || aerospace workspace --no-stdin prev']
ctrl-alt-cmd-j = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop down'
ctrl-alt-cmd-k = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop up'
#ctrl-alt-cmd-l = ['exec-and-forget aerospace focus right --boundaries-action fail || aerospace workspace next']
ctrl-alt-cmd-l = ['exec-and-forget aerospace focus right --boundaries-action fail || aerospace workspace --no-stdin next']

ctrl-alt-cmd-d = ['workspace-back-and-forth']
#ctrl-alt-cmd-d = ['focus-monitor --wrap-around next']

#ctrl-alt-cmd-i = ['exec-and-forget aerospace list-workspaces --monitor focused --empty no | aerospace workspace prev']
#ctrl-alt-cmd-o = ['exec-and-forget aerospace list-workspaces --monitor focused --empty no | aerospace workspace next']

ctrl-alt-cmd-1 = 'move-node-to-workspace 1 --focus-follows-window'
ctrl-alt-cmd-2 = 'move-node-to-workspace 2 --focus-follows-window'

# Try basic move first, then workspace switch 
ctrl-alt-cmd-shift-h = ['exec-and-forget aerospace move left --boundaries all-monitors-outer-frame --boundaries-action fail || aerospace move-node-to-workspace --no-stdin prev --focus-follows-window']
ctrl-alt-cmd-shift-j = ['exec-and-forget aerospace move down --boundaries all-monitors-outer-frame --boundaries-action fail || aerospace move-node-to-workspace 2 --focus-follows-window']
ctrl-alt-cmd-shift-k = ['exec-and-forget aerospace move up --boundaries all-monitors-outer-frame --boundaries-action fail || aerospace move-node-to-workspace 1 --focus-follows-window']
ctrl-alt-cmd-shift-l = ['exec-and-forget aerospace move right --boundaries all-monitors-outer-frame --boundaries-action fail || aerospace move-node-to-workspace --no-stdin next --focus-follows-window']

ctrl-alt-cmd-space = 'layout tiles accordion'
ctrl-alt-cmd-shift-space = 'layout horizontal vertical'

ctrl-alt-cmd-w = 'layout floating tiling'

[mode.service.binding]
r = ['reload-config', 'mode main']
q = ['exec-and-forget killall AeroSpace && open -a AeroSpace', 'mode main']
e = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout

backspace = ['close-all-windows-but-current', 'mode main']

ctrl-alt-cmd-h = ['move left', 'mode main']
ctrl-alt-cmd-j = ['move down', 'mode main']
ctrl-alt-cmd-k = ['move up', 'mode main']
ctrl-alt-cmd-l = ['move right', 'mode main']

#return to main mode
esc = ['mode main']

#this are no commands, they are rules (main or secondary)
[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'secondary'
